### ISSUE TITLE
Can't apply lastChange to two different object's properties

### ISSUE THREAD

**Issue by curcio** [google/qpp#1]
Once we select an attribute to inspect last changes it's not possible to select another attribute to inspect.

Way to reproduce: (using demo.js)

1 - Select attribute obj.prop from line 23 and click on button labeled 'lastChange' on the Querypoint Panel.
2 - Press the button in the html a couple of times, working as expected.
3 - Press the button labeled 'Click to Select Another Syntax Tree' on the panel.
4 - Select attribute condition.value on line 34 and click on button labeled 'lastChange' on the panel.
5 - Pressing the button in the html won't track the new attribute.

Furthermore, if the first attribute is selected again, pressing the button won't track the attribute.

**Comment by johnjbarton** [comment]
I guess you mean "property": DOM elements have attributes and JS objects properties.

Does lastChange on condition.value work if it is the first one tested?

**Comment by curcio** [comment]
Yes, I mean the property. If condition.value is the first one tested lastChange works as expected, but leads to another issue (issue 2)
