### ISSUE TITLE
CaseClause and DefaultClause not defined.

### ISSUE THREAD

**Issue by curcio** [google/qpp#108]
Debugger gives error when js file has a switch because CaseClause and DefaultClause are not defined in InsertingTransformer.js

To reproduce, add the following lines in the beggining of updateButton
  switch(obj.prop){
      case 1:
          console.error('Value is 1');
          break;
      default:
          console.error('Value is not 1');
  }

And use lastChange on obj.prop
Error message appears:
Uncaught ReferenceError: CaseClause is not defined InsertingTransformer.js:104

Replacing CaseClause and DefaultClause with Trees.CaseClause and Trees.DefaultClause in InsertingTransformer.js seems to make the error message go away.

**Comment by johnjbarton** [comment]
Yes that looks like the correct fix. Please add a test case (with a new .js test file)
