### ISSUE TITLE
Scripts loaded in different order than in html

### ISSUE THREAD

**Issue by curcio** [google/qpp#115]
When the debuggee gets reloaded, scripts get loaded in different random order than the one defined in the html.

The effect is very noticeable in kodemo since demo.js depends on object ko being defined in knockout.js, so half the time we get an error when loading the page (so no button appears).

To see that the order loaded is different, we can see the qp messages in the console corresponding to the start turns of each script load.

**Comment by johnjbarton** [comment]
This demo has four script tags correct? The RemoteWebPageProject simply uses document.querySelectorAll('script') to collect the scripts. Will that be in document order? As far as I can tell the rest of the code should be in order. We can divide the problem if we run with debug on in RemoteWebPageProject and compare the "Put ..." message object (scripts) to the start turn message order.
