### ISSUE TITLE
Problem with assignments in If condition

### ISSUE THREAD

**Issue by curcio** [google/qpp#116]
There is a problem when there is an assignment in an If condition (I suppose it will happen also for assignments in while).

I'll upload a test that shows the problem in tests/ifDemo

Open qpd.html and press the button. The number in the button increases with each click.
Open qpp and select obj.prop in line 13 and select lastChange.
Press button in debuggee and the number stays in 0.

The problem is in the bar() function. If you look at the resulting code in demo.js.js after pressing last change it says:
49: var name = 'value';
65: var __qp_388_5 = other;
77: if ((other = name) === 'value') __qp_382_3[__qp_388_5] = __qp_391_1;

Variable 'other' gets assigned value but __qp_388_5 isn't modified.

**Comment by johnjbarton** [comment]
Hmm. My original plan was to linearize everything then apply last change. Unfortunately I've forgotten why I switched.

Maybe out was just the complexity of the generated code.

But in the mean time the all tracing got added to linearize.

**Comment by johnjbarton** [comment]
Now that I look at the code: all-tracing was not added to linearize. Rather, linearize marks trees to be traced and QPTreeWriter adds the tracing. The 'if' example is the tip of the iceberg, 'for()' loops etc won't work as we have it now.

So the correct implementation:
- Linearize every tree,
- if lastChange then add write-barriers in ValueChangeTransformer.
- if allTracing then add tracing in QPTreeWriter.

The tricky parts are the interactions:
- Don't add write-barriers for writes only added by Linearize.
- Don't add tracing inside of write-barriers.

So we need to
- study how Linearize operates on assignments and 
- decide if the positive signal from Linearize (tree.traceId) or the negative signal (tree.doNotTrace) is what we need or both.

**Comment by johnjbarton** [comment]
Fixed by 4674a1888b511a1ae62ddb2339c83eed1d9d0294
