### ISSUE TITLE
Last change on same property of probably the same object at a different location

### ISSUE THREAD

**Issue by curcio** [google/qpp#12]
In demo.js when selected obj.prop on line 23, doing last change, and then obj.prop on lne 35 it doesn't do anthing.

Can't test what happens other way around because of issue #2

**Comment by johnjbarton** [comment]
To check that a trace of 'prop' was the lastChange on the object selected by the user, we store `obj` from `obj.prop` on `window.__qp.propertyChanges['prop'].objectTraced`.  When the second request for tracing 'prop' comes in we are overwriting the `.objectTraced`: BUG
