### ISSUE TITLE
Browsing through asynchronous turns

### ISSUE THREAD

**Issue by curcio** [google/qpp#120]
At the moment each asynchronous turn displays in which turn it was triggered. However the UI doesn't allow to explore easily the turns that were triggered previously.

**Comment by curcio** [comment]
I'll reopen the issue to fix the comments in the commit. Also, browsing through turns shouldn't be limited to asynchronous turns and it would be useful to be able to see what events were triggered in certain turn.

**Comment by johnjbarton** [comment]
Another suggestion: show more info in the Turn drop down. With just the turn number we have to look at each entry to decide what they mean.
