### ISSUE TITLE
Selecting three properties to view last change

### ISSUE THREAD

**Issue by curcio** [google/qpp#13]
In demo.js on function bar(), selecting last change on condition.value, then last value obj.prop, then condition.prop, when pressing the button it doesn't show last changes of the last selected property.

The same happens if the order is condition.value, condition.prop, obj.prop.

**Comment by johnjbarton** [comment]
I believe this is working correctly now, it was a duplicate of issue #12. Please check and close if you agree. Note that the obj.prop trace should be empty because the if block is never executed.

**Comment by curcio** [comment]
I made some tests and it seems it's working properly now.
