### ISSUE TITLE
Feature: Collapse loads in scrubberBox

### ISSUE THREAD

**Issue by curcio** [google/qpp#14]
Sometimes log becomes to big to explore comfortably. Being able to collapse turns would allow an easier navigation.

**Comment by johnjbarton** [comment]
One suggestion: use CSS transformations to create a 'fish-eye' viewer.

I'm imagining a non-linear display:

(1)(2)(3)[tiny boxes .....| --- regular size boxes --- | .....tiny boxes]

where (n) are collapsed load numbers, tiny boxes are scrubber box items scaled down, and | --- regular --- | is a region around the mouse where the boxes are enlarged.

**Comment by curcio** [comment]
Ok, I'm going to break it down in pieces in order to do small commits (and because they're funcional on they're own).

I changed the title to describe better the issue.

Submitted 2d41ae8dddeb602fc236c84dac4c143f795b1b08
