### ISSUE TITLE
Token Events won't work after lastChange found

### ISSUE THREAD

**Issue by curcio** [google/qpp#2]
When trying to change the inspected element the mouseOver over the source won't detect the token correctly. Only 'BLOCK' tokens are selected even if mouse is over some attribute in the block.

Way to reproduce: (using demo.js)

1 - Select attribute condition.value from line 34 and click on button labeled 'lastChange' on the Querypoint Panel.
2 - Press the button in the html a couple of times, working as expected.
3 - Press the button labeled 'Click to Select Another Syntax Tree' on the panel.
4 - Try to select another attribute (eg: obj.prop in line 23). Going over the attribute will try to select the entire block.

**Comment by johnjbarton** [comment]
I _think_ I fixed this one. Please add the qpp git commit title at the HEAD of your log.

**Comment by johnjbarton** [comment]
The new script-preprocessor change fixed this issue.

**Comment by johnjbarton** [comment]
QPFunctionPreambleTransformer runs every time we reload the page and it adds some lines at the beginning of each function. These lines have no source locations and thus they confuse the token finder.

We could either tell the token finder to ignore tokens without locations or mark the preamble lines to avoid them in the token finder or both.
