### ISSUE TITLE
Two buttons appearing when using Last Change.

### ISSUE THREAD

**Issue by curcio** [google/qpp#52]
Two buttons appear on the demo when using last change.

Without pressing any buttons in the console, select obj.prop and click last change. Two buttons appear and the warning 'This is your first warning' appears two times, when onLoad should be called only once.

**Comment by johnjbarton** [comment]
1. Open qpd.html, debug with qpp
2. Reload devtoolsExtended,
3. Open Querypoint panel
4. click obj.prop in line 23
5. click lastChange
   The qpd.html page has two Try Me buttons.

OR.
1. Reload devtoolsExtended,
2. Open Querypoint panel
3. click Reload with QP runtime.

**Comment by johnjbarton** [comment]
The turn counter also goes to 2

**Comment by johnjbarton** [comment]
Is this 100% reproducable for you?

I find that it happens _almost_ every time but sometimes I only get one button.  The testRunner never sees two buttons.

**Comment by johnjbarton** [comment]
If I 
1. Reload devtoolsExtended
2. Use the Console panel to set window.location = "http://localhost:8686/test/qpd.html"
Then continue as above, the two buttons do NOT appear.

Since the testRunner uses the window.location to reset the page, that is why it fails to reproduce this problem.

**Comment by johnjbarton** [comment]
The bug does appear if I use Control+R on the Console panel before opening the QP panel.
