### ISSUE TITLE
Can't select another syntax tree after many traces

### ISSUE THREAD

**Issue by curcio** [google/qpp#55]
After many trace messages the button that allows to click another syntax tree goes of screen.
1. open qpd.html, debug with qpp
2. click obj.prop on line 23
3. click last change
4. press the button on qpd.html several times
5. after certain amount of clicks the button is unclickable.

Should we place the button on top of the trace messages? Or should we make this part scrollable?

**Comment by johnjbarton** [comment]
I guess you mean:
5. after enough clicks, the "Click to Select Another Syntax Tree" is off the screen and cannot be click.

**Comment by johnjbarton** [comment]
I suppose the solution depends upon how much of a CSS wizarad you are...

To me a good UI would grow the traceViewModel until the Click to Select button reached the bottom of the hover door target, then older traces would be hidden unless you scroll to them.
