### ISSUE TITLE
Remove tooltip from message indicators

### ISSUE THREAD

**Issue by curcio** [google/qpp#56]
Tooltips are overlapping with the drop down containing turn and event information

**Comment by johnjbarton** [comment]
Here is a different solution: move the new box down enough to allow the tooltip to show.

And what if the new box was taller...tall enough to show all of the events in a turn...with the one the mouse is hovering centered and highlighted.

Then the tooltip is a compact format and he new box is a bit more information as well as links and context (the other events).  This taller form would give a lot more sense of the role of the event esp. in more complex apps.

**Comment by johnjbarton** [comment]
Here are some tooltips that have a 'placement' option
http://billpull.github.com/knockout-bootstrap/#tooltip
