### ISSUE TITLE
Messages in information box don't match with where the mouse is positioned in the scrubber bar.

### ISSUE THREAD

**Issue by curcio** [google/qpp#63]
The problem is that at the moment we use an array to store turns in the log, but if these turns have no messages then we don't add a turn's information.

At the moment there are some turns corresponding to script tags that have no console events. So the inforation for turn 6 isn't actually in the 6th position.

What I'm not sure is if we should display turn information if no console message happened in that turn. The only way of noticing right now is checking in which turns the messages happen.

Should we display these empty turns in some way?

**Comment by johnjbarton** [comment]
We certainly need to represent turns with no developer created messages. In fact if our work is wildly successful, we might imagine less use of console.log().

One solution would be to insert a message into the log describing the turn, then this message is represented by the (currently white) turn marker.  This would also help visually connect the log and logscrubber.
