### ISSUE TITLE
Allow adding a marker/separator in scrubber bar 

### ISSUE THREAD

**Issue by curcio** [google/qpp#65]
Allow to add an turn separator in the end of the scrubber bar to distinguish between old/load turns and events the developer triggered later.

**Comment by johnjbarton** [comment]
Here I am imagining the UX for this feature:

To start the user sees a small green (say) box on the end of the boxes in the logScrubber. The box has a small black dot. 

The user clicks on the box/dot, the box splits into two boxes, left one with an X right one with a red dot, text (in between) "Reproduce your bug" or "Operate on Your Page". Perhaps the WebApp window is focused as a hint.

The user operates on the WebApp, eg clicks a button.

The events triggered by the user stream in to the logScrubber. These events are surrounded on the left by the box  with an X and on the right by the box with a red dot. 

User clicks the red dot to end the marking session (recording).  red dot turns into a 'play' arrow.

Clicking the X box resets to original, moving the single black dot to the end.

Clicking the play arrow fires the event(s).

The play arrow is implicitly hit for operations like lastChange.
