### ISSUE TITLE
[traceElements] Can't trace elements when using "Reload Page with Querypoint Runtime"

### ISSUE THREAD

**Issue by curcio** [google/qpp#97]
When using the buttons in the initial panel the trace element feature isn't working.

When using "Reload Page with Trace Expressions" the button in the debuggee disappears as soon as the "Trace Element" is clicked. Maybe related with issue #70

**Comment by curcio** [comment]
Apparently this is the same issue as #70 in the case of using last change after all in file. When using last change some trees have undefined location but traceur assumes that if tree.location !== null then tree.location.start is defined which results in error when tree.location is undefined.

**Comment by johnjbarton** [comment]
Yup, Reload with Trace Expressions would be allInFile and traceElement is essentially lastChange. So a test case for #70 should also cover this one.

**Comment by johnjbarton** [comment]
Closing this because I removed the link on the onOpenPanel page that triggers it.
